apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ekscluster
  region: ap-southeast-1

nodeGroups:
  - name: node1
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
      publicKeyName:  key12
  - name: node2
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
      publicKeyName:  key12
