apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: far-lwcluster
  region: ap-southeast-1

nodeGroups:
  - name: node1
    instanceType: t2.micro
    desiredCapacity: 3
    ssh:
      publicKeyName:  key12

fargateProfiles:
  - name: fargate-default
    selectors:
     - namespace: kube-system
     - namespace: default